Repository bcgov/moh-prime, pull requests merged in 2019-12, with the labels that each got.

#103 Basic Email Service
  .gitattributes
  docker-compose.yml
  openshift/dotnet-webapi.dc.yaml
  prime-angular-frontend/Dockerfile
  prime-dotnet-webapi/Dockerfile
  prime-dotnet-webapi/PrimeConstants.cs
  prime-dotnet-webapi/Services/DefaultEmailService.cs
  prime-dotnet-webapi/Services/IEmailService.cs
  prime-dotnet-webapi/Startup.cs
  prime-dotnet-webapi/entrypoint.sh
  prime-dotnet-webapi/openshift.dockerfile
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ ☕, ༼ つ ◕_◕ ༽つ 🍝, ༼ つ ◕_◕ ༽つ 🍪, ༼ つ ◕_◕ ༽つ 🍱🍛🥪

#152 Enrolment Review
  prime-angular-frontend/src/app/config/config-code.pipe.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.html
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.scss
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.spec.ts
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.ts
  prime-angular-frontend/src/app/shared/pipes/default.pipe.spec.ts
  prime-angular-frontend/src/app/shared/pipes/default.pipe.ts
  prime-angular-frontend/src/app/shared/pipes/postal.pipe.ts
  prime-angular-frontend/src/app/shared/shared.module.ts
  prime-angular-frontend/src/scss/_font.scss
  prime-angular-frontend/src/scss/material/_material-fixes.scss
Labels: Frontend, Ready For Review

#153 Dashboard Navigation
  prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts
  prime-angular-frontend/src/scss/material/_material-fixes.scss
Labels: Frontend, Ready For Review

#140 HealthCheck
  openshift/dotnet-webapi.dc.yaml
  prime-dotnet-webapi/.editorconfig
  prime-dotnet-webapi/Startup.cs
  prime-dotnet-webapi/prime.csproj
Labels: Backend, Ready For Review

#155 Refactor PrimeUtils
  prime-dotnet-webapi/ApiDbContext.cs
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
  prime-dotnet-webapi/Controllers/EnrolmentCertificatesController.cs
  prime-dotnet-webapi/Extensions/ClaimsPrincipalExensions.cs
  prime-dotnet-webapi/Infrastructure/PrimeUserAuthHandler.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#156 Add in Emails on manual status change
  openshift/dotnet-webapi.dc.yaml
  prime-dotnet-webapi/PrimeConstants.cs
  prime-dotnet-webapi/Services/DefaultEmailService.cs
  prime-dotnet-webapi/Services/DefaultEnrolleeService.cs
  prime-dotnet-webapi/Services/IEmailService.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍱🍛🥪

#157 Updated header to show first and last, not first and first name (for Jason's sanity)
  prime-angular-frontend/src/app/core/services/utils.service.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.ts
  prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.spec.ts
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.ts
  prime-angular-frontend/src/app/shared/pipes/enrolment.pipe.ts
Labels: Frontend, Ready For Review

#158 Updates and Fixes
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.scss
Labels: Frontend, Ready For Review

#161 Fix Tests
  prime-dotnet-webapi-tests/.editorconfig
  prime-dotnet-webapi-tests/.gitignore
  prime-dotnet-webapi-tests/Mocks/EmailServiceMock.cs
  prime-dotnet-webapi-tests/Mocks/EnrolleeServiceMock.cs
  prime-dotnet-webapi-tests/Services/DefaultEnrolleeService.Tests.cs
  prime-dotnet-webapi-tests/Services/EmailService.Tests.cs
  prime-dotnet-webapi-tests/TestStartup.cs
  prime-dotnet-webapi-tests/Utils/TestUtils.cs
  prime-dotnet-webapi/Models/Enrollee.cs
  prime-dotnet-webapi/Startup.cs
Labels: Backend, Ready For Review

#162 Fix for profile contact not showing until email is filled in
  prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.html
Labels: Frontend, Ready For Review

#163 Updated UX/UI
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.html
  prime-angular-frontend/src/app/modules/enrolment-certificate/pages/certificate/certificate.component.html
  prime-angular-frontend/src/app/modules/enrolment-certificate/pages/certificate/certificate.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/confirmation/confirmation.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/device-provider/device-provider.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.scss
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.scss
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.ts
  prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.html
  prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.scss
  prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.ts
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/components/forms/address/address.component.html
  prime-angular-frontend/src/app/shared/components/page-subheader/page-subheader.component.scss
  prime-angular-frontend/src/scss/material/_material-fixes.scss
Labels: Frontend, Ready For Review

#166 Fix Review Self Declaration
  prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.html
Labels: Frontend, Ready For Review

#170 Fixes for Enrollees/Enrollee
  prime-dotnet-webapi/Models/Enrollee.cs
  prime-dotnet-webapi/Services/DefaultEnrolleeService.cs
Labels: Backend, Ready For Review

#167 Enrolment Declined
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
  prime-angular-frontend/src/app/modules/enrolment-certificate/enrolment-certificate-routing.module.ts
  prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
  prime-angular-frontend/src/app/modules/enrolment/enrolment.module.ts
  prime-angular-frontend/src/app/modules/enrolment/enrolment.routes.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined-access-agreement/declined-access-agreement.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/declined-access-agreement/declined-access-agreement.component.scss
  prime-angular-frontend/src/app/modules/enrolment/pages/declined-access-agreement/declined-access-agreement.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined-access-agreement/declined-access-agreement.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined/declined.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/declined/declined.component.scss
  prime-angular-frontend/src/app/modules/enrolment/pages/declined/declined.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined/declined.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/guards/enrolment.guard.ts
  prime-angular-frontend/src/app/shared/components/alert/alert.component.ts
  prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts
Labels: Frontend, Ready For Review

#149 Installing Schemaspy
  Jenkinsfile
  Jenkinsfile.promotion
  Jenkinsfile.tools
  docker-compose.yml
  functions.bash
  openshift/dotnet-webapi.dc.yaml
  openshift/schemaspy.bc.yaml
  openshift/schemaspy.dc.yaml
  player.sh
  prime-dotnet-webapi/openshift.dockerfile
  schemaspy.conf
  schemaspy/Caddyfile
  schemaspy/Dockerfile
  schemaspy/LICENSE
  schemaspy/deployment.yaml
  schemaspy/docker-compose.yml
  schemaspy/openshift.dockerfile
  schemaspy/start.sh
Labels: CI/CD, Ready For Review

#171 Front-End Tests
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined-access-agreement/declined-access-agreement.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/declined/declined.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.ts
Labels: Frontend, Ready For Review

#148 Pharmanet College Licence Validation
  openshift/dotnet-webapi.dc.yaml
  prime-dotnet-webapi-tests/Mocks/PharmanetApiServiceMock.cs
  prime-dotnet-webapi-tests/Services/PharmanetApiService.Tests.cs
  prime-dotnet-webapi/Models/PharmanetCollegeRecord.cs
  prime-dotnet-webapi/PrimeConstants.cs
  prime-dotnet-webapi/Services/DefaultPharmanetAPIService.cs
  prime-dotnet-webapi/Services/IPharmanetApiService.cs
  prime-dotnet-webapi/Startup.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍱🍛🥪

#180 Re-add auth
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
Labels: Backend, Bug, Ready For Review, ༼ つ ◕_◕ ༽つ 🍝

#181 Refactoring and cleanup of enrollee controller + service
  prime-dotnet-webapi-tests/Controllers/EnrolleesController.Tests.cs
  prime-dotnet-webapi-tests/Mocks/BaseMockService.cs
  prime-dotnet-webapi-tests/Mocks/EnrolleeServiceMock.cs
  prime-dotnet-webapi-tests/Services/DefaultEnrolleeService.Tests.cs
  prime-dotnet-webapi-tests/Utils/TestUtils.cs
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
  prime-dotnet-webapi/Extensions/ClaimsPrincipalExensions.cs
  prime-dotnet-webapi/Services/DefaultEnrolleeService.cs
  prime-dotnet-webapi/Services/IEnrolleeService.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍱🍛🥪

#177 Zap Scanning
  Jenkinsfile
  Jenkinsfile.tools
  api.conf
  openshift/sonar-scanner.dc.yaml
  player.sh
  prime-angular-frontend/openshift.dockerfile
  prime-angular-frontend/package-lock.json
  sonar-scanner/Dockerfile
  sonar-scanner/entrypoint.bash
  sonar-scanner/openshift.dockerfile
  tests.bash
  zap.conf
Labels: CI/CD, Ready For Review

#185 Assign Privileges
  prime-dotnet-webapi-tests/Mocks/PrivilegeMockService.cs
  prime-dotnet-webapi-tests/Services/DefaultEnrolleeService.Tests.cs
  prime-dotnet-webapi-tests/Utils/TestUtils.cs
  prime-dotnet-webapi/ApiDbContext.cs
  prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs
  prime-dotnet-webapi/Models/AssignedPrivilege.cs
  prime-dotnet-webapi/Models/DefaultPrivilege.cs
  prime-dotnet-webapi/Services/DefaultEnrolleeService.cs
  prime-dotnet-webapi/Services/DefaultPrivilegeService.cs
  prime-dotnet-webapi/Services/IPrivilegeService.cs
  prime-dotnet-webapi/Startup.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ ☕

#186 Database Configuration Files
  prime-dotnet-webapi/ApiDbContext.cs
  prime-dotnet-webapi/Configuration/CollegeConfiguration.cs
  prime-dotnet-webapi/Configuration/CollegeLicenseConfiguration.cs
  prime-dotnet-webapi/Configuration/CollegePracticeConfiguration.cs
  prime-dotnet-webapi/Configuration/CountryConfiguration.cs
  prime-dotnet-webapi/Configuration/JobNameConfiguration.cs
  prime-dotnet-webapi/Configuration/LicenseConfiguration.cs
  prime-dotnet-webapi/Configuration/OrganizationTypeConfiguration.cs
  prime-dotnet-webapi/Configuration/PracticeConfiguration.cs
  prime-dotnet-webapi/Configuration/ProvinceConfiguration.cs
  prime-dotnet-webapi/Configuration/StatusConfiguration.cs
  prime-dotnet-webapi/Configuration/StatusReasonConfiguration.cs
  prime-dotnet-webapi/Migrations/20191214002905_Privileges.cs
  prime-dotnet-webapi/Migrations/20191217154601_Initial.Designer.cs
  prime-dotnet-webapi/Migrations/20191217154601_Initial.cs
  prime-dotnet-webapi/Migrations/20191220200330_Initial.Designer.cs
  prime-dotnet-webapi/Migrations/20191220200330_Initial.cs
  prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs
Labels: Backend, Ready For Review

#189 Updates for SRI
  prime-angular-frontend/package.json
  prime-angular-frontend/src/index.html
Labels: Frontend, Ready For Review

#184 Update how enrollee status is marked for editing
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.html
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
  prime-dotnet-webapi/Services/DefaultEnrolleeService.cs
Labels: Frontend, Ready For Review

#187 Security hardening of NGINX, Angular
  Jenkinsfile.promotion
  Jenkinsfile.tools
  functions.bash
  openshift/dotnet-webapi.bc.yaml
  openshift/dotnet-webapi.dc.yaml
  openshift/postgresql.bc.yaml
  openshift/postgresql.dc.yaml
  openshift/schemaspy.dc.yaml
  player.sh
  prime-angular-frontend/angular.json
  prime-angular-frontend/nginx.conf
  prime-angular-frontend/nginx.template.conf
  prime-angular-frontend/src/robots.txt
  prime-dotnet-webapi/appsettings.json
  prime-dotnet-webapi/openshift.dockerfile
  tests.bash
Labels: Frontend, Ready For Review
