Repository bcgov/moh-prime, pull requests merged in 2020-07, with the labels that each got.

#691 Fixing PVC
  document-manager/backend/.env-prime-local
  document-manager/backend/Dockerfile
  document-manager/backend/openshift.dockerfile
  openshift/document-manager-base.bc.yaml
  openshift/document-manager.dc.yaml
Labels: Backend, CI/CD

#697 Add back KEYCLOAK_TOKEN_URL env var
  docker-compose.yml
  document-manager/backend/Dockerfile
  openshift/dotnet-webapi.dc.yaml
Labels: (ノ益 )ノ彡┻━┻, Backend, CI/CD

#694 PRIME-865 Phone field is listed as optional but should be mandatory
  prime-angular-frontend/src/app/modules/site-registration/shared/services/organization-form-state.service.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/services/site-form-state.service.ts
Labels: Frontend, Ready For Review

#693 PRIME-771 Manually Triggering a reminder email in Admin isn't adding the event onto Events Log
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  openshift/dotnet-webapi.dc.yaml
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
  prime-dotnet-webapi/Services/EmailService.cs
Labels: Backend, Ready For Review

#695 PRIME-870 OrgBook name field refinements
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-information/organization-information.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-information/organization-information.component.ts
  prime-angular-frontend/src/app/shared/components/alert/alert.component.html
  prime-angular-frontend/src/app/shared/components/alert/alert.component.ts
  prime-angular-frontend/src/scss/material/_material-overrides.scss
Labels: Frontend, Ready For Review

#699 Troubleshooting templates
  openshift/angular-frontend.dc.yaml
Labels: (ノ益 )ノ彡┻━┻, CI/CD

#698 PRIME-740 Use CHES for Email
  openshift/dotnet-webapi.dc.yaml
  prime-dotnet-webapi/PrimeConstants.cs
  prime-dotnet-webapi/Services/Clients/Email/CHESBearerTokenHandler.cs
  prime-dotnet-webapi/Services/Clients/Email/CHESClient.cs
  prime-dotnet-webapi/Services/Clients/Email/IChesClient.cs
  prime-dotnet-webapi/Services/Clients/Email/ISmtpEmailClient.cs
  prime-dotnet-webapi/Services/Clients/Email/SmtpEmailClient.cs
  prime-dotnet-webapi/Services/EmailService.cs
  prime-dotnet-webapi/Startup.cs
Labels: Backend, Ready For Review

#701 PRIME-902 - Enrolment Certificate Bug
  prime-dotnet-webapi/Models/EnrolmentCertificate.cs
  prime-dotnet-webapi/Services/EnrolmentCertificateService.cs
Labels: Backend, Bug, ༼ つ ◕_◕ ༽つ 🍝

#702 Updated BCSC Link
  prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
Labels: Frontend, Ready For Review

#705 Feature/prime 720 self decl download
  openshift/angular-frontend.bc.yaml
  openshift/angular-frontend.dc.yaml
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  openshift/document-manager.pod.dc.yaml
  prime-angular-frontend/openshift.dockerfile
  prime-angular-frontend/src/app/app-config.module.ts
  prime-angular-frontend/src/app/core/resources/organization-resource.service.ts
  prime-angular-frontend/src/app/core/services/utils.service.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/review-status-content/review-status-content.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/review-status-content/review-status-content.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/business-licence/business-licence.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/business-licence/business-licence.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-agreement/organization-agreement.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-agreement/organization-agreement.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-overview/organization-overview.component.scss
  prime-angular-frontend/src/app/modules/site-registration/pages/site-overview/site-overview.component.scss
  prime-angular-frontend/src/app/modules/site-registration/shared/models/business-licence.model.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/models/signed-agreement.model.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/services/site-registration-resource.service.ts
  prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.scss
  prime-angular-frontend/src/app/shared/components/header/header.component.scss
  prime-angular-frontend/src/app/shared/components/site/site-review/site-review.component.html
  prime-angular-frontend/src/app/shared/models/enrolment.model.ts
  prime-angular-frontend/src/environments/environment.prod.template.ts
  prime-angular-frontend/src/environments/environment.ts
  prime-dotnet-webapi-tests/Mocks/EnrolleeServiceMock.cs
  prime-dotnet-webapi-tests/Unit Tests/MinorUpdateRules.Tests.cs
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
  prime-dotnet-webapi/Controllers/OrganizationsController.cs
  prime-dotnet-webapi/Models/SelfDeclarationDocument.cs
  prime-dotnet-webapi/Models/SiteRegistration/SignedAgreement.cs
  prime-dotnet-webapi/Services/DocumentService.cs
  prime-dotnet-webapi/Services/EmailService.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
  prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs
  prime-dotnet-webapi/Services/interfaces/IDocumentService.cs
  prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs
  prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeProfileViewModel.cs
Labels: (ノ益 )ノ彡┻━┻, Backend, Frontend, Ready For Review

#709 HOTFIX: Get Document Manager to actually deploy for real to Test and Prod
  Jenkinsfile.promotion
Labels: CI/CD, ༼ つ ◕_◕ ༽つ 🍝

#707 PRIME-879 - Enable Comunity Pharmacy in Dev/Test
  documentation/Keycloak settings/realm-export-dev.json
  documentation/Keycloak settings/realm-export-prod.json
  documentation/Keycloak settings/realm-export-test.json
Labels: Documentation, Ready For Review, ༼ つ ◕_◕ ༽つ ☕

#712 HOTFIX: Make sure the correct version of Document Manager is deployed to Demo
  Jenkinsfile.promotion
Labels: CI/CD, Ready For Review, ༼ つ ◕_◕ ༽つ 🍝

#715 Revert GPID Update Endpoint
  prime-dotnet-webapi/Controllers/EnrolleesController.cs
  prime-dotnet-webapi/Services/SubmissionService.cs
  prime-dotnet-webapi/Services/interfaces/ISubmissionService.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#708 PRIME-611: Construction of Test Branch and refactor Release
  Jenkinsfile.promotion
  Jenkinsfile.release
  Jenkinsfile.test
  functions.bash
Labels: (ノ益 )ノ彡┻━┻, CI/CD, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#720 Remove PVC
  Jenkinsfile
  openshift/document-manager-ephemeral.dc.yaml
  openshift/postgresql.ephemeral.dc.yaml
Labels: CI/CD

#721 PRIME-931 Fix Submit breaking if Verifiable Credential API fails
  prime-dotnet-webapi/Services/SubmissionService.cs
Labels: Backend, Ready For Review

#724 PRIME # - Unbreak backend tests
  prime-dotnet-webapi-tests/ModelFactories/EnrolleeFactory.cs
  prime-dotnet-webapi-tests/Unit Tests/EmailService.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/EnrolmentCertificateService.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/SubmissionService.Tests.cs
Labels: Backend, Ready For Review

#718 PRIME-930 Web Client: Login Update
  prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
  prime-angular-frontend/src/app/modules/auth/pages/site/site.component.html
  prime-angular-frontend/src/app/modules/auth/shared/styles/landing-page.scss
Labels: Frontend, Ready For Review

#722 PRIME-929 - Disable Multiple Sites and Fix for redirect issue when view an existing site from the drop down menu
  prime-angular-frontend/src/app/modules/site-registration/pages/organizations/organizations.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/organizations/organizations.component.ts
Labels: Frontend, Ready For Review

#710 PRIME-895 API Unit Test
  Jenkinsfile
  functions.bash
  player.sh
  prime-angular-frontend/src/environments/environment.prod.template.ts
  prime-angular-frontend/src/environments/environment.prod.ts
  sonar-scanner/sonar-runner.bash
  tests.bash
Labels: CI/CD, Ready For Review

#706 PRIME-892 Verifiable Credential obfuscated webhook url
  prime-dotnet-webapi/Controllers/WebhooksController.cs
  prime-dotnet-webapi/PrimeConstants.cs
  prime-dotnet-webapi/Services/Clients/VerifiableCredential/IVerifiableCredentialClient.cs
  prime-dotnet-webapi/Services/Clients/VerifiableCredential/VerifiableCredentialClient.cs
  prime-dotnet-webapi/Services/VerifiableCredentialService.cs
Labels: Backend, DO NOT MERGE

#732 PRIME # - SonarQube Updates
  prime-angular-frontend/src/scss/mixins/_agreements.scss
  prime-dotnet-webapi/Controllers/OrganizationsController.cs
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
  prime-dotnet-webapi/Controllers/SitesController.cs
  prime-dotnet-webapi/Models/AccessTerms/LicenseClassClause.cs
  prime-dotnet-webapi/Models/Enrollee.cs
  prime-dotnet-webapi/Services/AdminService.cs
  prime-dotnet-webapi/Services/OrganizationService.cs
  prime-dotnet-webapi/Services/PrivilegeService.cs
  prime-dotnet-webapi/Services/RazorConverterService.cs
  prime-dotnet-webapi/Services/VerifiableCredentialService.cs
  prime-dotnet-webapi/Views/Helpers/ApologyDocument.cshtml
  prime-dotnet-webapi/Views/OrganizationAgreement.cshtml
  prime-dotnet-webapi/Views/OrganizationAgreementPdf.cshtml
  prime-dotnet-webapi/Views/SiteRegistrationReview.cshtml
  prime-dotnet-webapi/Views/TermsOfAccess.cshtml
  prime-dotnet-webapi/docker-compose.yml
Labels: Backend, Ready For Review

#733 Fix/prime 937 migrate self declaration data
  prime-dotnet-webapi/Migrations/20200617210846_SelfDeclarationCreation.cs
Labels: Database, ༼ つ ◕_◕ ༽つ ☕

#734 Adding security to frontend per SonarQube
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
Labels: Frontend

#729 PRIME-887 Adding NGINX to proxy docman
  openshift/angular-frontend.bc.yaml
  openshift/angular-frontend.dc.yaml
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  openshift/dotnet-webapi.dc.yaml
  prime-angular-frontend/nginx.template.conf
  prime-angular-frontend/nginxdev.conf
  prime-angular-frontend/nginxprod.conf
  prime-angular-frontend/nginxtest.conf
Labels: Backend, CI/CD, Frontend, Ready For Review

#740 PRIME # Updates to site and info page footer and links
  prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
  prime-angular-frontend/src/app/modules/auth/pages/site/site.component.html
Labels: Frontend, Ready For Review

#739 Disable Verifiable Credentials
  prime-angular-frontend/src/app/modules/enrolment/shared/components/next-steps-infographic/next-steps-infographic.component.html
  prime-dotnet-webapi/Services/SubmissionService.cs
Labels: Backend, Frontend, Ready For Review

#742 Jenkins reduction for pipeline consumption
  Jenkinsfile
  Jenkinsfile.promotion
  Jenkinsfile.release
  Jenkinsfile.test
  openshift/angular-frontend.bc.yaml
  openshift/angular-frontend.dc.yaml
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  openshift/dotnet-webapi.dc.yaml
  player.sh
  prime-angular-frontend/openshift.dockerfile
Labels: CI/CD, Ready For Review

#745 FIX: Ensuring PVC claim is binded to pod volume
  openshift/document-manager.dc.yaml
Labels: CI/CD, Ready For Review

#746 1 MB File Upload Chunk Size
  prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
Labels: Frontend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#748 Un-Ignore Document GUID
  prime-dotnet-webapi/Models/BaseDocumentUpload.cs
Labels: Backend, Bug, Ready For Review

#752 FIX: Force Document Manager Migrate to wait for PostgreSQL deployment completion
  docker-compose.yml
  document-manager/backend/Dockerfile
  document-manager/backend/app.sh
  document-manager/backend/openshift.dockerfile
  document-manager/backend/requirements.txt
  openshift/document-manager-ephemeral.dc.yaml
  openshift/document-manager.dc.yaml
  openshift/postgresql.dc.yaml
  openshift/postgresql.ephemeral.dc.yaml
Labels: Backend, CI/CD

#751 Max Filesize of 3MB
  prime-angular-frontend/package-lock.json
  prime-angular-frontend/package.json
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-agreement/organization-agreement.component.ts
  prime-angular-frontend/src/app/modules/site-registration/site-registration.module.ts
  prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
  prime-angular-frontend/src/app/shared/shared.module.ts
Labels: (ノ益 )ノ彡┻━┻, Frontend, Ready For Review

#749 FEATURE: Provide Production with Hotfix stage
  Jenkinsfile.production
  Jenkinsfile.test
Labels: CI/CD, Ready For Review

#753 PRIME-927 Pharmacist's can't request remote access
  prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certification-form/college-certification-form.component.html
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts
  prime-angular-frontend/src/app/shared/enums/college-licence-class.enum.ts
Labels: Frontend, Ready For Review
