Repository bcgov/moh-prime, pull requests merged in 2021-08, with the labels that each got.

#1475 e2e test for entering Health Authority organization info
  prime-e2e-tests/Admin.Tests.cs
  prime-e2e-tests/BaseTest.cs
  prime-e2e-tests/TestParameters.cs
  prime-e2e-tests/WebDriverExtensions.cs
  prime-e2e-tests/run-tests.cmd
Labels: Ready For Review

#1480 FIX: License Code not showing for condensed nurses
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
Labels: Bug, Frontend, Ready For Review

#1482 Reverted button label to Enable Editing
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-actions/site-registration-actions.component.html
Labels: Frontend, Ready For Review

#1444 PRIME-1454 Error messaging UX
  prime-angular-frontend/src/app/core/resources/logger-resource.service.ts
  prime-angular-frontend/src/app/core/services/error-handler.service.ts
  prime-angular-frontend/src/app/core/services/web-api-logger.service.ts
  prime-angular-frontend/src/app/lib/modules/ngx-material/ngx-material.module.ts
  prime-angular-frontend/src/app/shared/classes/dialog-logger.ts
  prime-angular-frontend/src/app/shared/components/dialogs/content/error-logger/error-logger.component.html
  prime-angular-frontend/src/app/shared/components/dialogs/content/error-logger/error-logger.component.scss
  prime-angular-frontend/src/app/shared/components/dialogs/content/error-logger/error-logger.component.spec.ts
  prime-angular-frontend/src/app/shared/components/dialogs/content/error-logger/error-logger.component.ts
  prime-angular-frontend/src/app/shared/pipes/format-date.pipe.ts
  prime-angular-frontend/src/app/shared/shared.module.ts
  prime-dotnet-webapi/Controllers/ClientLogsController.cs
  prime-dotnet-webapi/Services/ClientLogService.cs
  prime-dotnet-webapi/Services/interfaces/IClientLogService.cs
Labels: Frontend, Ready For Review

#1481 Site fix - initialize business licence list
  prime-dotnet-webapi/Models/SiteRegistration/Site.cs
Labels: Backend, Ready For Review

#1494 Feature/PRIME 1748 + PRIME 1650 next steps rework
  prime-angular-frontend/src/app/lib/utils/date-utils.class.ts
  prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
  prime-angular-frontend/src/app/modules/enrolment/enrolment.module.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/components/dashboard/dashboardv1.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/components/next-steps-infographic/next-steps-infographic.component.html
  prime-angular-frontend/src/app/modules/enrolment/shared/components/next-steps-infographic/next-steps-infographic.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/components/next-steps-infographic/next-steps-infographic.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.ts
  prime-angular-frontend/src/app/shared/components/alerts/expiry-alert/expiry-alert.component.ts
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html
  prime-angular-frontend/src/app/shared/components/infographic/infographic.component.html
  prime-angular-frontend/src/app/shared/components/infographic/infographic.component.scss
  prime-angular-frontend/src/app/shared/components/infographic/infographic.component.spec.ts
  prime-angular-frontend/src/app/shared/components/infographic/infographic.component.ts
  prime-angular-frontend/src/app/shared/shared.module.ts
  prime-angular-frontend/src/assets/global-full.svg
  prime-angular-frontend/src/assets/global.svg
Labels: Frontend, Ready For Review

#1496 Run migrations during pod initialization
  infrastructure/prime-app-ephemeral-template.yml
  infrastructure/prime-app-template.yml
Labels: DevOps

#1513 Fix Tests
  prime-angular-frontend/src/app/config/config.module.ts
  prime-angular-frontend/src/app/config/config.service.spec.ts
  prime-angular-frontend/src/app/core/modules/keycloak/keycloak.module.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/health-authorities/authorized-users-page/authorized-users-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/site-banner-page/site-banner-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/site-banner-page/site-banner-page.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/banner-maintenance/banner-maintenance.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/banner-maintenance/banner-maintenance.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/contextual-enrolment-confirmation/contextual-enrolment-confirmation.component.spec.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/collection-notice-page/collection-notice-page.component.spec.ts
Labels: Frontend, Ready For Review

#1518 Fix so Enrollment and Site Registration tests should be now working
  prime-e2e-tests/Admin.Tests.cs
  prime-e2e-tests/BaseTest.cs
  prime-e2e-tests/Enrollment.Tests.cs
  prime-e2e-tests/SiteRegistrationTests.cs
  prime-e2e-tests/run-tests.cmd
Labels: Ready For Review

#1522 PRIME-1750 Remove HIBC email from notifications on ***pharmacy*** site reg
  prime-dotnet-webapi/Controllers/SitesController.cs
  prime-dotnet-webapi/Services/EmailRenderingService.cs
  prime-dotnet-webapi/Services/EmailService.cs
  prime-dotnet-webapi/Services/interfaces/IEmailRenderingService.cs
  prime-dotnet-webapi/Services/interfaces/IEmailService.cs
Labels: Backend, Ready For Review

#1521 PRIME 1779 filter paper enrollees
  prime-angular-frontend/src/app/modules/adjudication/shared/components/search-form/search-form.component.ts
  prime-dotnet-webapi/Services/EnrolleeService.cs
Labels: Frontend, Backend, Ready For Review

#1523 Testing PR with reduced coverage
  .github/workflows/test-pr.yml
Labels: DO NOT MERGE

#1537 Fix/filter fix to test
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
Labels: Bug, Ready For Review

#1533 PRIME-1775 Fix TOA drop-down in Paper Enrollees
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/upload-page/upload-overview.component.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/upload-page/upload-page.component.html
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/upload-page/upload-page.component.ts
  prime-angular-frontend/src/app/shared/enums/agreement-type.enum.ts
Labels: Frontend, Ready For Review

#1541 Fix/cherry pick test changes
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
  prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
Labels: Ready For Review

#1535 [OPS] Add resource limits to PR deployments
  infrastructure/prime-app-ephemeral-template.yml
Labels: Ready For Review, DevOps

#1517 PRIME-1563 Angular Upgrade v12
  prime-angular-frontend/.browserslistrc
  prime-angular-frontend/.eslintrc.json
  prime-angular-frontend/Dockerfile.dev
  prime-angular-frontend/angular.json
  prime-angular-frontend/openshift.dockerfile
  prime-angular-frontend/package-lock.json
  prime-angular-frontend/package.json
  prime-angular-frontend/sonar-project.properties
  prime-angular-frontend/src/app/app-routing.module.ts
  prime-angular-frontend/src/app/lib/classes/abstract-enrolment-page.class.ts
  prime-angular-frontend/src/app/lib/classes/abstract-overview.class.ts
  prime-angular-frontend/src/app/lib/modules/ngx-busy/busy-loading/busy-loading.component.html
  prime-angular-frontend/src/app/modules/auth/shared/models/bceid-user.model.ts
  prime-angular-frontend/src/app/modules/auth/shared/models/paper-enrollee-user.model.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-form-state.service.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment.service.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page-form-state.class.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/shared/services/gis-enrolment.service.ts
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/authorized-user-page/authorized-user-form.model.ts
  prime-angular-frontend/src/app/modules/health-auth-site-reg/shared/services/authorized-user.service.ts
  prime-angular-frontend/src/app/modules/health-auth-site-reg/shared/services/health-auth-site-reg.service.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/care-setting-page/care-setting-form-state.class.ts
  prime-angular-frontend/src/app/modules/phsa-eforms/pages/bcsc-demographic/bcsc-demographic.component.spec.ts
  prime-angular-frontend/src/app/modules/provisioner-access/pages/certificate/certificate.component.html
  prime-angular-frontend/src/app/modules/site-registration/shared/services/organization.service.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/services/site.service.ts
  prime-angular-frontend/src/app/shared/components/collection-notice-container/collection-notice-container.component.ts
  prime-angular-frontend/src/app/shared/components/forms/access-code-form/access-code-form.component.spec.ts
  prime-angular-frontend/src/app/shared/components/pages/page-subheader/page-subheader.component.html
  prime-angular-frontend/src/environments/environment.ts
  prime-angular-frontend/src/polyfills.ts
  prime-angular-frontend/src/scss/material/_material-core.scss
  prime-angular-frontend/src/scss/material/_material-theme.scss
  prime-angular-frontend/src/test.ts
  prime-angular-frontend/src/test/mocks/mock-access-token.service.ts
  prime-angular-frontend/src/test/mocks/mock-auth.service.ts
  prime-angular-frontend/src/test/mocks/mock-authorized-user.service.ts
  prime-angular-frontend/src/test/mocks/mock-config.ts
  prime-angular-frontend/src/test/mocks/mock-enrolment.service.ts
  prime-angular-frontend/src/test/mocks/mock-organization.service.ts
  prime-angular-frontend/src/test/mocks/mock-site.service.ts
  prime-angular-frontend/tslint.json
Labels: Frontend, Ready For Review

#1545 FIX: Wrong param id used
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-notes/adjudicator-notes.component.ts
Labels: Bug, Ready For Review

#1497 VC Updates
  docker-compose.yml
  documentation/VerifiableCredentials.md
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
Labels: Documentation, Frontend, Ready For Review

#1532 PRIME-1755 GC Collect Endpoint
  prime-dotnet-webapi/Controllers/UtilController.cs
Labels: Backend, Ready For Review

#1543 [ops] startupProbe needs a long timeoutSeconds threshold
  infrastructure/prime-app-ephemeral-template.yml
  infrastructure/prime-app-template.yml
Labels: Ready For Review, DevOps

#1542 [ops] fix hpr url in production
  .github/workflows/build-main.yml
Labels: Ready For Review, DevOps

#1519 Fix to nginx.conf for PLR connections
  infrastructure/prime-app-ephemeral-template.yml
  infrastructure/prime-app-template.yml
  prime-angular-frontend/nginx.conf
  prime-angular-frontend/nginx.template.conf
  prime-angular-frontend/nginxdev.conf
  prime-angular-frontend/nginxprod.conf
  prime-angular-frontend/nginxtest.conf
  prime-angular-frontend/openshift.nginx.conf
Labels: Ready For Review, DevOps

#1556 Upgrade Diagnostics
  prime-dotnet-webapi/Controllers/DiagnosticsController.cs
  prime-dotnet-webapi/Controllers/UtilController.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#1510 Innovate CodeClimate
  .codeclimate.yml
  .github/workflows/test-pr.yml
  .gitignore
  prime-angular-frontend/karma.conf.js
  prime-angular-frontend/package.json
  prime-angular-frontend/src/app/modules/adjudication/pages/email-notification-view-page/email-notification-view-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-adjudicator-notes/enrollee-adjudicator-notes.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-banner-list-page/enrollee-banner-list-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-banner-page/enrollee-banner-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-toa-maintenance-view-page/enrollee-toa-maintenance-view-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/health-authorities/authorized-user-page/authorized-user-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/health-authorities/authorized-users-page/authorized-users-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/license-classes-maintenance-page/license-classes-maintenance-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/metabase-reports/metabase-reports.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/site-adjudicator-notes/site-adjudicator-notes.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/site-banner-list-page/site-banner-list-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-notes/adjudicator-notes.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/authorized-user-review/authorized-user-review.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/banner-list-view/banner-list-view.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/contextual-enrolment-confirmation/contextual-enrolment-confirmation.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/health-auth-authorized-users-view/health-auth-authorized-users-view.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/maintenance-container/maintenance-container.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/plr-info/plr-info.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/plr-info/plr-info.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/search-form/search-form.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/search-form/search-form.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-container/site-registration-container.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-tabs/site-registration-tabs.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/bceid-demographic/bceid-demographic.component.spec.ts
  prime-angular-frontend/src/test/mocks/mock-config.service.ts
  prime-dotnet-webapi-tests/.codeclimate.yml
  prime-dotnet-webapi-tests/Integration/EnrolleeIntegration.Tests.cs
  prime-dotnet-webapi-tests/ModelFactories/EnrolleeFactory.cs
  prime-dotnet-webapi-tests/Unit Tests/EnrolleeAgreementService.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/RazorConverterService.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/SiteStatusStateEngine.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/SoapService.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/SubmissionService.Tests.cs
Labels: CI/CD, Ready For Review, 💡 Innovation Days 💡

#1565 Fix Github Check Warning
  prime-dotnet-webapi-tests/Unit Tests/SoapService.Tests.cs
Labels: Backend, Ready For Review, ༼ つ ◕_◕ ༽つ 🍪

#1562 PRIME 1355: Deploy Cron Jobs
  infrastructure/openshift/send-renewal-emails.cron.yml
  infrastructure/prime-app-template.yml
  infrastructure/update-email-statuses.cron.yml
Labels: Ready For Review, DevOps
