Repository bcgov/moh-prime, pull requests merged in 2022-01, with the labels that each got.

#1867 PRIME-2029 gis initial feedback
  prime-angular-frontend/src/app/lib/modules/dashboard/components/dashboard-header/dashboard-header.component.html
  prime-angular-frontend/src/app/lib/modules/dashboard/dashboard.module.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/enrollee-information-page/enrollee-information-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-user-page/ldap-user-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-user-page/ldap-user-page.component.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/shared/modules/gis-login/gis-login-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/shared/modules/gis-login/gis-login-page.component.ts
  prime-angular-frontend/src/app/shared/components/pages/page-footer/page-footer.component.html
  prime-angular-frontend/src/app/shared/components/pages/page-footer/page-footer.component.ts
Labels: Frontend, Ready For Review

#1903 PRIME-2060 Fix Code Climate
  .github/workflows/test-pr.yml
Labels: Ready For Review

#1853 PRIME-1760 - Remote practitioner changes
  prime-angular-frontend/src/app/lib/models/remote-user.model.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page-form-state.class.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.ts
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
  prime-angular-frontend/src/test/mocks/mock-community-site.service.ts
  prime-dotnet-webapi-tests/Unit Tests/CommunitySiteService.Tests.cs
  prime-dotnet-webapi/Services/CommunitySiteService.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/CommunitySiteUpdateModel.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/SiteRemoteUserUpdateModel.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/_SiteMappingProfile.cs
Labels: Frontend

#1883 PRIME-2053 do not send renewal emails to absent enrollees
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
  prime-dotnet-webapi/Models/EnrolleeAbsence.cs
  prime-dotnet-webapi/Services/EmailService.cs
Labels: Backend, Ready For Review

#1919 [ops] Fix migrations
  infrastructure/prime-app-template.yml
Labels: Ready For Review, DevOps

#1920 Fix sentry for backend unit tests
  prime-dotnet-webapi-tests/TestStartup.cs
Labels: Ready For Review

#1932 Fix PharmaNet dummy client
  prime-dotnet-webapi/HttpClients/College Licence API/DummyCollegeLicenceClient.cs
Labels: Ready For Review

#1912 PRIME-2064 Post-ODR API test improvements
  infrastructure/cron-jobs/parse_api_response.py
  infrastructure/cron-jobs/retrieve-pnet-logs.cron.yml
  infrastructure/cron-jobs/retrieve-pnet-logs.sh
Labels: Ready For Review

#1941 Fix When Selecting HA for enrollee overview validation for OBO site
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-form-state.service.ts
Labels: Bug, Frontend, Ready For Review

#1930 PRIME-2021 Paper Enrolment Status Should Not Be Under Review
  prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.ts
  prime-angular-frontend/src/app/shared/enums/enrolment-status.enum.ts
Labels: Frontend, Ready For Review

#1949 PRIME-2076 Paper enrolments flagged as always manual
  prime-dotnet-webapi/Services/EnrolleePaperSubmissionService.cs
Labels: Backend, Ready For Review

#1936 Fix Email Performance
  prime-dotnet-webapi/Models/Email/EmailTemplate.cs
  prime-dotnet-webapi/Services/EmailRenderingService.cs
  prime-dotnet-webapi/Services/Razor/RazorConverterService.cs
  prime-dotnet-webapi/Services/interfaces/IRazorConverterService.cs
Labels: Ready For Review, ༼ つ ◕_◕ ༽つ 🍱🍛🥪, (ノ益 )ノ彡┻━┻

#1931 Feature/prime 2055 effective license lookup
  prime-dotnet-webapi-tests/Unit Tests/LookupService.Tests.cs
  prime-dotnet-webapi/Models/Certifications/License.cs
  prime-dotnet-webapi/Services/LookupService.cs
Labels: Backend, Ready For Review

#1955 PRIME-2090 wordsmithing self declaration
  prime-angular-frontend/src/app/lib/data/self-declaration-questions.ts
Labels: Frontend, Ready For Review

#1952 PRIME-2085 wordsmithing
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/site-address-page/site-address-page.component.html
Labels: Frontend, Ready For Review

#1951 PRIME-2081 PRIME enrolment complete wordsmithing
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
Labels: Frontend, Ready For Review

#1964 fix remote user navigation and form state management
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.ts
Labels: Bug, Frontend, Ready For Review

#1968 PRIME-2091 Switch IdentityProvider for GIS
  prime-angular-frontend/src/app/modules/gis-enrolment/shared/modules/gis-login/gis-login-page.component.ts
Labels: Frontend

#1959 Feature/prime 2062 minor update im reg
  prime-dotnet-webapi-tests/Unit Tests/AgreementEngine.Tests.cs
  prime-dotnet-webapi-tests/Unit Tests/MinorUpdateRules.Tests.cs
  prime-dotnet-webapi-tests/Utils/InMemoryDbTest.cs
  prime-dotnet-webapi/Models/Agreements/AgreementVersion.cs
  prime-dotnet-webapi/Models/Enrollee.cs
  prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs
  prime-dotnet-webapi/Services/SubmissionRulesService.cs
  prime-dotnet-webapi/Services/SubmissionService.cs
  prime-dotnet-webapi/Services/interfaces/ISubmissionRulesService.cs
Labels: Backend, Needs Tests

#1973 Fix Keycloak Client for Users with no Attributes
  prime-dotnet-webapi/HttpClients/Keycloak Administration/KeycloakApiDefinitions.cs
Labels: Backend, Ready For Review, (ノ益 )ノ彡┻━┻

#1942 PRIME-2079 Post-second ODR API test improvements
  infrastructure/cron-jobs/parse_api_response.py
  infrastructure/cron-jobs/retrieve-pnet-logs.cron.yml
  infrastructure/cron-jobs/retrieve-pnet-logs.sh
Labels: Ready For Review

#1963 PRIME-2080 User needs to sign a new TOA
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
  prime-dotnet-webapi/Controllers/EnrolleeAgreementsController.cs
  prime-dotnet-webapi/Models/Agreements/AgreementGroup.cs
  prime-dotnet-webapi/Models/Agreements/AgreementType.cs
  prime-dotnet-webapi/Services/EnrolleeAgreementService.cs
  prime-dotnet-webapi/Services/interfaces/IEnrolleeAgreementService.cs
Labels: Frontend, Backend, Needs Tests, Ready For Review

#1977 fix add pharm tech toa to admin action select
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-actions/adjudicator-actions.component.ts
Labels: Bug, Ready For Review

#1978 Fix db migration for PRIME-2097
  prime-dotnet-webapi/Migrations/20220129234305_AddPharmacyTechnicianToa.cs
  prime-dotnet-webapi/Migrations/20220131232115_AddPharmacyTechnicianToa.Designer.cs
  prime-dotnet-webapi/Migrations/20220131232115_AddPharmacyTechnicianToa.cs
  prime-dotnet-webapi/Migrations/ApiDbContextModelSnapshot.cs
Labels: Ready For Review, Database
