Repository bcgov/moh-prime, pull requests merged in 2022-03, with the labels that each got.

#2062 PRIME-2151 Wordsmithing continued
  prime-angular-frontend/src/app/modules/enrolment/pages/absence-management-page/absence-management-page.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/bcsc-demographic/bcsc-demographic.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-claim-page/organization-claim-page.component.html
  prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
  prime-angular-frontend/src/environments/environment.prod.ts
Labels: Frontend, Ready For Review

#1940 Fix/downgrade sentry to be compatible with oc sentry
  prime-dotnet-webapi-tests/TestStartup.cs
  prime-dotnet-webapi/Configuration/PrimeConfigurationObjects.cs
  prime-dotnet-webapi/Helpers/ISentryErrorReporter.cs
  prime-dotnet-webapi/Helpers/SentryErrorReporter.cs
  prime-dotnet-webapi/Helpers/SentryMiddleWare.cs
  prime-dotnet-webapi/PrimeConfiguration.cs
  prime-dotnet-webapi/Program.cs
  prime-dotnet-webapi/Startup.cs
  prime-dotnet-webapi/appsettings.json
  prime-dotnet-webapi/prime.csproj
Labels: Ready For Review

#2048 PRIME-2144 SPIKE: Dependabot Recommendations
  .github/dependabot.yml
Labels: Ready For Review

#2060 PRIME-2147 logout issue
  prime-angular-frontend/src/app/modules/enrolment/shared/components/dashboard/dashboardv1.component.ts
Labels: Ready For Review

#2033 PRIME-2030: Expire obo pharm tech TOA
  prime-dotnet-webapi/Migrations/20220215012218_ExpireOBOPharmTechTOAApril1st.Designer.cs
  prime-dotnet-webapi/Migrations/20220215012218_ExpireOBOPharmTechTOAApril1st.cs
Labels: Ready For Review, Database

#2084 TEST3
  .github/workflows/test-pr.yml
  prime-angular-frontend/src/app/modules/adjudication/test-codeclimate/test-codeclimate.component.ts
Labels: DO NOT MERGE

#2091 TEST 7
  .github/workflows/test-pr.yml
  prime-angular-frontend/src/app/modules/adjudication/test-codeclimate/test-codeclimate.component.ts
Labels: DO NOT MERGE

#2092 TEST8
  .github/workflows/test-pr.yml
  prime-angular-frontend/src/app/modules/adjudication/test-codeclimate/test-codeclimate.component.ts
Labels: DO NOT MERGE

#2095 TEST
  .github/workflows/test-pr.yml
  prime-angular-frontend/src/app/modules/adjudication/test-codeclimate/test-codeclimate.component.ts
Labels: DO NOT MERGE

#2068 Update to create-mock-data utility
  utilities/create-mock-data/ModelFactories/CertificationFactory.cs
  utilities/create-mock-data/ModelFactories/OboSiteFactory.cs
  utilities/create-mock-data/Program.cs
Labels: Ready For Review, .NET

#2081 Deleted pip-angular-frontend
  pip-angular-frontend/.browserslistrc
  pip-angular-frontend/.dockerignore
  pip-angular-frontend/.editorconfig
  pip-angular-frontend/.gitignore
  pip-angular-frontend/Dockerfile
  pip-angular-frontend/README.md
  pip-angular-frontend/angular.json
  pip-angular-frontend/karma.conf.js
  pip-angular-frontend/package.json
  pip-angular-frontend/src/app/app-routing.module.ts
  pip-angular-frontend/src/app/app.component.html
  pip-angular-frontend/src/app/app.component.scss
  pip-angular-frontend/src/app/app.component.spec.ts
  pip-angular-frontend/src/app/app.component.ts
  pip-angular-frontend/src/app/app.module.ts
  pip-angular-frontend/src/assets/.gitkeep
  pip-angular-frontend/src/environments/environment.prod.ts
  pip-angular-frontend/src/environments/environment.ts
  pip-angular-frontend/src/favicon.ico
  pip-angular-frontend/src/index.html
  pip-angular-frontend/src/main.ts
  pip-angular-frontend/src/polyfills.ts
  pip-angular-frontend/src/styles.scss
  pip-angular-frontend/src/test.ts
  pip-angular-frontend/tsconfig.app.json
  pip-angular-frontend/tsconfig.json
  pip-angular-frontend/tsconfig.spec.json
  pip-angular-frontend/yarn.lock
Labels: Ready For Review

#2076 PRIME-2160 wordsmithing
  prime-angular-frontend/src/app/lib/constants.ts
Labels: Frontend, Ready For Review

#2088 PRIME-2148 Add reference number to subject line of email to hibc
  prime-dotnet-webapi/Services/EmailRenderingService.cs
  prime-dotnet-webapi/Services/EmailService.cs
  prime-dotnet-webapi/Services/interfaces/IEmailRenderingService.cs
Labels: Backend, Ready For Review

#2099 PRIME-2169 GIS Wordsmithing
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-user-page/ldap-user-page.component.html
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/submission-confirmation-page/submission-confirmation-page.component.html
Labels: Frontend, Ready For Review

#2098 PRIME-2158 do not send renewal emails to enrollees who already renewed
  prime-dotnet-webapi/Services/EmailService.cs
Labels: Backend, Ready For Review

#2106 PRIME-2189 Resubmitting a declined site submission will not resubmit
  prime-angular-frontend/src/app/modules/site-registration/pages/overview-page/overview-page.component.ts
Labels: Frontend, Ready For Review

#2104 Real time wordsmithing from meeting with business
  prime-angular-frontend/src/app/modules/adjudication/pages/license-classes-maintenance-page/license-classes-maintenance-page.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/contextual-enrolment-confirmation/contextual-enrolment-confirmation.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/maintenance-container/maintenance-container.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/access-code/access-code.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/access-locked/access-locked.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/id-submission/id-submission.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/paper-enrollee-returnees-page/paper-enrollee-returnees-page.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access-addresses/remote-access-addresses.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/submission-confirmation/submission-confirmation.component.html
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment.service.ts
  prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.html
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/authorized-user-approved-page/authorized-user-approved-page.component.html
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/authorized-user-next-steps-page/authorized-user-next-steps-page.component.html
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/site-information-page/site-information-page.component.html
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/regulatory-page/regulatory-overview.component.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/regulatory-page/regulatory-page.component.html
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/self-declaration-page/self-declaration-overview.component.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/self-declaration-page/self-declaration-page.component.html
  prime-angular-frontend/src/app/modules/phsa-eforms/pages/access-code/access-code.component.html
  prime-angular-frontend/src/app/modules/sat-eforms/shared/modules/sat-eforms-login-page/sat-eforms-login-page.component.html
  prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
  prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
  prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-self-declarations/enrollee-self-declarations.component.html
  prime-angular-frontend/src/app/shared/components/progress-indicator/progress-indicator.component.ts
Labels: Frontend, Ready For Review

#2097 PRIME-2071 code climate diff changes
  .github/workflows/test-pr.yml
Labels: Ready For Review

#2110 PRIME-2183 Can't navigate from CareSettings page in paper enrolment
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/care-setting-page/care-setting-form-state.class.ts
Labels: Frontend, Ready For Review

#2115 Fix/site business licence upload
  prime-angular-frontend/src/app/modules/site-registration/pages/business-licence-page/business-licence-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/overview-page/overview-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/overview-page/overview-page.component.ts
  prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html
  prime-dotnet-webapi/Controllers/SitesController.cs
Labels: Bug, Frontend, Backend, Ready For Review

#2112 Fix/prime 2181 overview validation health auth enrollees
  prime-angular-frontend/src/app/modules/enrolment/pages/bcsc-demographic/bcsc-demographic.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/paper-enrollee-returnees-page/paper-enrollee-returnees-page.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access-addresses/remote-access-addresses.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access-addresses/remote-access-addresses.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
  prime-angular-frontend/src/app/modules/enrolment/shared/classes/enrolment-profile-page.class.ts
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
Labels: Frontend, Ready For Review

#2111 PRIME-2179 allow addition of multiple addresses for paper enrolment
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-overview/enrollee-overview.component.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/demographic-page/demographic-form-state.class.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/demographic-page/demographic-form.model.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/demographic-page/demographic-overview.component.ts
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/demographic-page/demographic-page.component.html
  prime-angular-frontend/src/app/modules/paper-enrolment/pages/demographic-page/demographic-page.component.ts
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/models/enrollee.model.ts
  prime-dotnet-webapi/Configuration/Database/Unseeded Tables/AddressConfiguration.cs
  prime-dotnet-webapi/Models/Addresses/Address.cs
  prime-dotnet-webapi/Models/Enrollee.cs
  prime-dotnet-webapi/Services/EnrolleePaperSubmissionService.cs
  prime-dotnet-webapi/ViewModels/Common/_CommonMappingProfile.cs
  prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeDTO.cs
  prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeViewModel.cs
  prime-dotnet-webapi/ViewModels/Enrollee/_EnrolleeMappingProfile.cs
  prime-dotnet-webapi/ViewModels/Paper Enrollees/PaperEnrolleeDemographicViewModel.cs
Labels: Frontend, Backend, Ready For Review

#2114 Feature/prime 2145 site pagination
  prime-angular-frontend/src/app/core/resources/organization-resource.service.ts
  prime-angular-frontend/src/app/core/resources/site-resource.service.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-container/site-registration-container.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.ts
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-tabs/site-registration-tabs.component.html
  prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-tabs/site-registration-tabs.component.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/models/site-registration.model.ts
  prime-dotnet-webapi/Controllers/OrganizationsController.cs
  prime-dotnet-webapi/Controllers/SitesController.cs
  prime-dotnet-webapi/Models/Api/OrganizationSearchOptions.cs
  prime-dotnet-webapi/Services/CommunitySiteService.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
  prime-dotnet-webapi/Services/OrganizationService.cs
  prime-dotnet-webapi/Services/interfaces/ICommunitySiteService.cs
  prime-dotnet-webapi/Services/interfaces/IOrganizationService.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/CommunitySiteAdminListViewModel.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/_SiteMappingProfile.cs
Labels: Frontend, Backend, Ready For Review

#2108 PRIME-2178 add unit tests to adjudication module
  prime-angular-frontend/src/app/modules/adjudication/pages/email-notification-list-page/email-notification-list-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/email-notification-view-page/email-notification-view-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-access-term-enrolment/enrollee-access-term-enrolment.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-adjudicator-documents/enrollee-adjudicator-documents.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-banner-list-page/enrollee-banner-list-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-banner-page/enrollee-banner-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-enrolments/enrollee-enrolments.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-events/enrollee-events.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-events/enrollee-events.component.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-maintenance-page/enrollee-maintenance-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-overview/enrollee-overview.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-toa-maintenance-list-page/enrollee-toa-maintenance-list-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-toa-maintenance-view-page/enrollee-toa-maintenance-view-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/license-classes-maintenance-page/license-classes-maintenance-page.component.spec.ts
  prime-angular-frontend/src/app/modules/adjudication/pages/limits-conditions-clauses/limits-conditions-clauses.component.spec.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
Labels: Frontend, Ready For Review
