Repository bcgov/moh-prime, pull requests merged in 2022-09, with the labels that each got.

#2191 PRIME-2280 Add validation to ensure the Renewal date is in the future
  prime-angular-frontend/src/app/lib/validators/form-control.validators.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.ts
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
Labels: Frontend, Ready For Review

#2195 PRIME-2275 API to return HPDIDs that have been updated
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
  prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs
Labels: Backend, Ready For Review

#2199 PRIME-2285 TOA logic update
  prime-dotnet-webapi/DTOs/AgreementEngine/AgreementEngineDto.cs
  prime-dotnet-webapi/Engines/AgreementEngine Internal/CertificationDigest.cs
  prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs
Labels: Backend, Ready For Review

#2193 Fix - Hide Other Licence Field in Regular Enrolment
  prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-overview/enrollee-overview.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment.service.ts
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.ts
  prime-angular-frontend/src/test/mocks/mock-enrolment.service.ts
Labels: Ready For Review

#2202 PRIME-2292 Upper Case PharmaNet ID
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.scss
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
  prime-dotnet-webapi/Services/EnrolleeService.cs
Labels: Frontend, Ready For Review

#2200 PRIME-2222 Unlock Profile changes
  prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
  prime-angular-frontend/src/app/shared/enums/enrollee-status-action.enum.ts
  prime-dotnet-webapi-tests/Unit Tests/SubmissionStateEngine.Tests.cs
  prime-dotnet-webapi/Controllers/SubmissionsController.cs
  prime-dotnet-webapi/Engines/EnrolleeStatusStateEngine.cs
  prime-dotnet-webapi/Models/Api/EnrolleeStatusAction.cs
  prime-dotnet-webapi/Services/SubmissionService.cs
Labels: Backend, Ready For Review

#2208 Documentation for Cerner/CST
  documentation/GetUpdatedGpids-API.md
  documentation/HpdidLookup-API.md
Labels: Documentation, Ready For Review

#2204 PRIME-2271 Orgs with multiple sites in admin view are causing confusion
  prime-dotnet-webapi/Services/CommunitySiteService.cs
Labels: Backend, Ready For Review
