Repository bcgov/moh-prime, pull requests merged in 2023-11, with the labels that each got.

#2395 PRIME-2478 Support Multiple Organization for single SA
  prime-angular-frontend/src/app/core/resources/organization-resource.service.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-name-page/organization-name-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.scss
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/classes/abstract-routing-workflow-guard.class.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/guards/change-signing-authority.guard.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/guards/organization.guard.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/services/organization.service.ts
  prime-angular-frontend/src/test/mocks/mock-organization.service.ts
  prime-dotnet-webapi/Services/OrganizationService.cs
Labels: Frontend, Backend, Ready For Review

#2401 PRIME-2593 Fix failing `build-frontend`
  .github/workflows/build-demo.yml
  .github/workflows/build-develop.yml
  .github/workflows/build-main.yml
  .github/workflows/build-pr.yml
  .github/workflows/build-test.yml
Labels: Ready For Review, DevOps

#2405 PRIME-2594 Auto-approve Full Naturopaths that are only missing Birthdate in PharmaNet
  .github/workflows/test-pr.yml
  prime-dotnet-webapi/Controllers/SubmissionsController.cs
  prime-dotnet-webapi/HttpClients/College Licence API/DummyCollegeLicenceClient.cs
  prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs
  prime-dotnet-webapi/Services/SubmissionRulesService.cs
  prime-dotnet-webapi/Services/SubmissionService.cs
  prime-dotnet-webapi/Services/interfaces/ISubmissionRulesService.cs
  prime-dotnet-webapi/Services/interfaces/ISubmissionService.cs
Labels: Backend

#2406 PRIME-2594 Implement fix and address performance
  prime-dotnet-webapi/Services/SubmissionService.cs
Labels: Backend

#2399 PRIME-2591 bug fix on Organization Claim feature
  prime-dotnet-webapi/Controllers/OrganizationsController.cs
  prime-dotnet-webapi/Services/CommunitySiteService.cs
  prime-dotnet-webapi/Services/interfaces/ICommunitySiteService.cs
Labels: Backend
