Repository bcgov/moh-prime, pull requests merged in 2023-07, with the labels that each got.

#2354 PRIME-2462 - Clarify Site Name instruction
  prime-angular-frontend/src/app/shared/components/forms/site-information-form/site-information-form.component.html
Labels: Frontend, Ready For Review

#2355 fix - Update reporting back end process
  prime-dotnet-webapi/Controllers/JobsController.cs
  prime-dotnet-webapi/Services/ReportingService.cs
Labels: Backend

#2358 Fix performance issue on Reporting process - Populating Practitioner table
  prime-dotnet-webapi/Services/ReportingService.cs
Labels: Backend, Ready For Review

#2360 Reporting Process - Populate Practitioner - ignore record with null Practitioner ID
  prime-dotnet-webapi/Services/ReportingService.cs
Labels: Backend, Ready For Review

#2364 PRIME-2526 Issue with OrgBook searches
  prime-angular-frontend/src/app/core/services/web-api-logger.service.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/organization-name-page/organization-name-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/shared/services/org-book-resource.service.ts
  prime-dotnet-webapi/Controllers/ClientLogsController.cs
Labels: Frontend, Backend
