Repository bcgov/moh-prime, pull requests merged in 2023-05, with the labels that each got.

#2320 PRIME-2473 update hpdid lookup
  documentation/HpdidLookup-API.md
  prime-dotnet-webapi/Models/Api/EnrolleeCertDto.cs
  prime-dotnet-webapi/Models/Api/HpdidLookupResponse.cs
  prime-dotnet-webapi/Models/Statuses/ProvisionerEnrolmentStatusType.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
Labels: Backend

#2313 PRIME-2457 Handle invalid email address during SendEnrolleeRenewalEmails
  prime-dotnet-webapi/Controllers/EmailsController.cs
  prime-dotnet-webapi/HttpClients/Mail/ChesClient.cs
  prime-dotnet-webapi/Services/EmailService.cs
Labels: Backend

#2322 PRIME-2473 Further updates for HpdidLookup API
  documentation/HpdidLookup-API.md
  prime-dotnet-webapi/Models/Statuses/ProvisionerEnrolmentStatusType.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
Labels: Documentation, Backend

#2284 PRIME-2400 Update Practitioner Verification logic
  prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs
Labels: Backend, Ready For Review

#2251 PRIME-2373 SendRemoteUsersUpdatedAsync failed
  prime-dotnet-webapi/Services/EmailService.cs
Labels: Backend, Ready For Review

#2335 Revert "PRIME-2400 Update Practitioner Verification logic (#2284)"
  prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs
Labels: Backend, Ready For Review

#2252 PRIME-2374 fix obo-to-ru 500 error in log
  prime-dotnet-webapi/Controllers/SubmissionsController.cs
  prime-dotnet-webapi/Services/EnrolleeAgreementService.cs
  prime-dotnet-webapi/Services/EnrolleeService.cs
  prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs
Labels: Backend, Ready For Review

#2333 PRIME-2490 Update Self-declaration warning text
  prime-angular-frontend/src/app/shared/components/enrollee/enrollee-self-declarations/enrollee-self-declarations.component.html
Labels: Frontend, Ready For Review

#2338 PRIME-2494 fix Remote User matching logic
  prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.ts
  prime-dotnet-webapi/Services/SiteService.cs
  prime-dotnet-webapi/ViewModels/SiteRegistration/CertSearchViewModel.cs
Labels: Frontend, Backend, Ready For Review
