Repository bcgov/moh-prime, pull requests merged in 2024-01, with the labels that each got.

#2424 PRIME-2620 Login UI Change
  prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
Labels: Frontend, Ready For Review

#2431 PRIME-2624 fix server problem
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
Labels: Backend, Ready For Review

#2437 PRIME-2486 Remove inappropriate API originally for Medinet
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
Labels: Backend

#2438 PRIME-2640 Fix scary-looking production `apply-oc-template` error
  .github/workflows/build-main.yml
Labels: DevOps

#2441 PRIME-2647 Tweak current wording of "Only physicians and nurse practitioners are permitted to access PharmaNet remotely"
  prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
Labels: Frontend
