Repository bcgov/moh-prime, pull requests merged in 2024-05, with the labels that each got.

#2498 PRIME-2712 Remove "/info" from the PRIME URL in Renewal Email
  prime-dotnet-webapi/Services/EmailRenderingService.cs
Labels: Backend, Ready For Review

#2500 PRIME-2410 Copy of original PR #2174, with minor additions
  infrastructure/DBScripts/PharmanetTransactionLogs_Partition.sql
Labels: Database

#2502 PRIME-2528 Adjust what are acceptable characters in Alternative Name fields
  prime-angular-frontend/src/app/lib/validators/form-control.validators.ts
Labels: Frontend

#2494 PRIME-2708 Add pharmanet admin and tech support contact detail in admin HA site overview page
  prime-angular-frontend/src/app/modules/adjudication/pages/health-authorities/site-overview-page/site-overview-page.component.html
  prime-angular-frontend/src/app/modules/adjudication/pages/health-authorities/site-overview-page/site-overview-page.component.ts
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/administrator-page/administrator-overview.component.ts
  prime-angular-frontend/src/app/shared/components/health-auth-site-overview-container/health-auth-site-overview-container.component.html
  prime-angular-frontend/src/app/shared/components/health-auth-site-overview-container/health-auth-site-overview-container.component.ts
Labels: Frontend, Ready For Review

#2511 PRIME-2602 Add cron job template for refreshing materialized view
  infrastructure/cron-jobs/refresh-materialized-view.cron.yml
Labels: Backend, Ready For Review

#2507 PRIME-2721 Remove note requirement when assigning adjudicator
  prime-angular-frontend/src/app/shared/components/dialogs/content/claim-note/claim-note.component.html
  prime-angular-frontend/src/app/shared/components/dialogs/content/claim-note/claim-note.component.ts
Labels: Frontend, Ready For Review

#2516 PRIME-2737 Log token used to call `GetGpidDetail`
  prime-dotnet-webapi/Configuration/Auth/AuthenticationSetup.cs
Labels: Backend, Ready For Review
