Repository bcgov/moh-prime, pull requests merged in 2024-09, with the labels that each got.

#2564 PRIME-2767: Stale TOA assignment if original SD questions
  prime-angular-frontend/src/app/modules/enrolment/pages/collection-notice/collection-notice.component.ts
  prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
  prime-dotnet-webapi/Controllers/SubmissionsController.cs
  prime-dotnet-webapi/Services/EnrolleeAgreementService.cs
  prime-dotnet-webapi/Services/SubmissionService.cs
  prime-dotnet-webapi/Services/interfaces/IEnrolleeAgreementService.cs
Labels: Frontend, Backend, Ready For Review

#2558 PRIME-2764 Update validation to require only one email address for share GPID page
  prime-angular-frontend/src/app/lib/modules/forms/trim-space.directive.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/next-steps/next-steps.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/next-steps/next-steps.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
  prime-angular-frontend/src/app/shared/components/forms/email-form/email-form.component.html
  prime-angular-frontend/src/app/shared/components/forms/email-form/email-form.component.ts
  prime-angular-frontend/src/app/shared/shared.module.ts
Labels: Backend, Ready For Review

#2584 Fix building issue - codeclimate check error
  .github/workflows/test-pr.yml
Labels: Backend, Ready For Review

#2589 PRIME-2788 fix email error
  prime-angular-frontend/src/app/modules/enrolment/pages/next-steps/next-steps.component.ts
  prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
Labels: Frontend, Ready For Review

#2583 PRIME-2671 Update Site Renewal Message
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/overview-page/overview-page.component.html
  prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/site-management-page/site-management-page.component.ts
  prime-angular-frontend/src/app/modules/site-registration/pages/overview-page/overview-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.html
  prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.ts
Labels: Frontend, Ready For Review

#2591 PRIME-2789 Create Event Log entry associated with Enrollee when GetGpidDetail called
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
Labels: Backend, Ready For Review

#2592 PRIME-2789 - Adjustments based on demo feedback
  prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
Labels: Backend, Ready For Review
