Repository bcgov/moh-prime, pull requests merged in 2024-08, with the labels that each got.

#2559 Try to fix Document Manager timeout issue when enrollee accepting TOA
  prime-dotnet-webapi/HttpClients/Document Manager/DocumentManagerClient.cs
Labels: Backend, Ready For Review

#2560 PRIME-2748 Remove Site Registration Banner
  prime-angular-frontend/src/app/modules/site-registration/pages/next-steps-page/next-steps-page.component.html
Labels: Frontend, Ready For Review

#2561 Fix Document Manager vulnerabilities
  document-manager/backend/.env-local
  document-manager/backend/Dockerfile
  document-manager/backend/Dockerfile.migrate
  document-manager/backend/app/__init__.py
  document-manager/backend/app/docman/resources/document.py
  document-manager/backend/app/helper.py
  document-manager/backend/app/routes.py
  document-manager/backend/app/utils/custom_reqparser.py
  document-manager/backend/openshift.dockerfile
  document-manager/backend/requirements.txt
  document-manager/document-manager-base.dockerfile
  infrastructure/prime-app-ephemeral-template.yml
  infrastructure/prime-app-template.yml
Labels: Ready For Review, python

#2571 PRIME-2773 - Fix error on site submission
  prime-dotnet-webapi/HttpClients/Document Manager/DocumentManagerClient.cs
Labels: Backend, Ready For Review

#2572 PRIME-2771 fix black screen issue
  prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
  prime-angular-frontend/src/app/shared/enums/college-licence-class.enum.ts
  prime-angular-frontend/src/app/shared/enums/college-licence-grouping.enum.ts
Labels: Backend, Ready For Review
